tunnel: mybackend
credentials-file: C:/Users/anush/.cloudflared/880fb840-5bc1-4a09-991f-176cbb0a6b8c.json

# Connection settings to reduce timeout errors
retries: 5
grace-period: 30s

ingress:
  - hostname: api.sanoraindia.com
    service: http://localhost:3100   # your backend port
  - service: http_status:404

